import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import CartSpace from "../../Components/Carts/CartSpace";
import OrderSpace from "../../Components/order/OrderSpace";
import Topwall from "../../Components/Shop/TopWall/Topwall";


const Home: NextPage = () => {
  const router = useRouter();
  const gotoshop = ()=> router.push("/catalog")

  return (
    
    <>
    <Head>
      <title>Cactus | Order</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
    <Topwall title="Billing details" titleStyle="text-white" /> 
    <OrderSpace fetcher="gl"/>
  </>
  );
};

export default Home;
