import { type NextPage } from "next";
import Head from "next/head";
import ShopSpace from "../../Components/Shop/ShopSpace/ShopSpace";
import Sidebar from "../../Components/Shop/SideBar/SideBar";
import Topwall from "../../Components/Shop/TopWall/Topwall";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Cactus | shop</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Topwall/>
      <div className="sm:grid grid-cols-12">
        <div className="col-span-4 lg:col-span-3 bg-black p-1  ">
        <label htmlFor="my-modal-6" className=" bg-base-300 btn rounded-xl fixed bottom-3 right-4 z-50 p-4  sm:hidden">Shop Settings</label>
            <input type="checkbox" id="my-modal-6" className="modal-toggle" />
            <div className="onlymobile:modal onlymobile:modal-bottom sm:static">
              <div className="onlymobile:modal-box ">
                <Sidebar/>
                <div className="onlymobile:modal-action onlymobile:text-primary sm:hidden">
                  <label htmlFor="my-modal-6" className="btn">Close Shop Settings</label>
                </div>
              </div>
            </div>
            
        </div>
        <div className="col-span-8 lg:col-span-9">
          <ShopSpace 
          fetcher="https://fakestoreapi.com/products?limit=12" 
          title="" 
          footer="" 
          titleStyle="text-white"
          gridType={3} />
        </div>
      </div>
    </>
  );
};

export default Home;
