import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";


const Home: NextPage = () => {
  const router = useRouter();
  const gotoshop = ()=> router.push("/catalog")

  return (
    <>
      <Head>
        <title>Cactus | Order completed</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="text-center space-y-6 p-4">
        <h3 className="font-bold text-2xl">Your order is  <span className="text-primary">Completed</span></h3>
        <p className="text-secondary">Thank you for your order, our manager will contact you in couple minutes</p>
        <button onClick={gotoshop} className="btn btn-square btn-primary w-60">Return to shop</button>
        
      </div>
    </>
  );
};

export default Home;
