import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>404 error</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div>404 Error</div>
    </>
  );
};

export default Home;
