import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";


const Error404: NextPage = () => {
  const router = useRouter();
  const gotoshop = ()=> router.push("/catalog")

  return (
    <>
      <Head>
        <title>Cactus | Err404</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="text-center space-y-6 p-4">
        <h3 className="font-bold text-2xl">This page <span className="text-primary">doesn't exist</span></h3>
        <p className="text-secondary">If this is an unexpected behavior of the website please contact us and tell us about the problem</p>
        <button onClick={gotoshop} className="btn btn-square btn-primary w-60">Return to shop</button>
        
      </div>
    </>
  );
};

export default Error404;
