import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";
import HomeCover from "../Components/Home/HomeCover";
import State from "../Components/Home/State";
import ShopSpace from "../Components/Shop/ShopSpace/ShopSpace";
import BlogSpace from "../Components/Blog/BlogSpace/BlogSpace";


const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Cactus | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomeCover/>
        <State/>
        
        <ShopSpace 
        fetcher="https://fakestoreapi.com/products?limit=12" 
        title="Hot Promotions" 
        footer="" 
        titleStyle="text-base-100"
        discount={0.68}
        gridType={4} />

        <BlogSpace 
        fetcher="https://jsonplaceholder.typicode.com/posts?limit=6" 
        title="Top Blog Articles" 
        footer="" 
        titleStyle="text-base-100"/>
      </main>
    </>
  );
};

export default Home;
